python finetune_momentum.py clipped_data rgb 1 0
python finetune_momentum.py clipped_data flow 1 0
python finetune_momentum.py clipped_data rgb 2 0
python finetune_momentum.py clipped_data flow 2 0
python finetune_momentum.py clipped_data rgb 3 0
python finetune_momentum.py clipped_data flow 3 0
python finetune_momentum.py clipped_data rgb 4 0
python finetune_momentum.py clipped_data flow 4 0
python finetune_momentum.py clipped_data rgb 5 0
python finetune_momentum.py clipped_data flow 5 0
python finetune_momentum.py clipped_data rgb 6 0
python finetune_momentum.py clipped_data flow 6 0
python finetune_momentum.py clipped_data rgb 7 0
python finetune_momentum.py clipped_data flow 7 0
python finetune_momentum.py clipped_data rgb 8 0
python finetune_momentum.py clipped_data flow 8 0
python finetune_momentum.py clipped_data rgb 9 0
python finetune_momentum.py clipped_data flow 9 0
python finetune_momentum.py clipped_data rgb 10 0
python finetune_momentum.py clipped_data flow 10 0
python finetune_momentum.py clipped_data rgb 11 0
python finetune_momentum.py clipped_data flow 11 0
python finetune_momentum.py clipped_data rgb 12 0
python finetune_momentum.py clipped_data flow 12 0