python finetune_momentum.py clipped_data rgb 1 1
python finetune_momentum.py clipped_data flow 1 1
python finetune_momentum.py clipped_data rgb 2 1
python finetune_momentum.py clipped_data flow 2 1
python finetune_momentum.py clipped_data rgb 3 1
python finetune_momentum.py clipped_data flow 3 1
python finetune_momentum.py clipped_data rgb 4 1
python finetune_momentum.py clipped_data flow 4 1
python finetune_momentum.py clipped_data rgb 5 1
python finetune_momentum.py clipped_data flow 5 1
python finetune_momentum.py clipped_data rgb 6 1
python finetune_momentum.py clipped_data flow 6 1
python finetune_momentum.py clipped_data rgb 7 1
python finetune_momentum.py clipped_data flow 7 1
python finetune_momentum.py clipped_data rgb 8 1
python finetune_momentum.py clipped_data flow 8 1
python finetune_momentum.py clipped_data rgb 9 1
python finetune_momentum.py clipped_data flow 9 1
python finetune_momentum.py clipped_data rgb 10 1
python finetune_momentum.py clipped_data flow 10 1
python finetune_momentum.py clipped_data rgb 11 1
python finetune_momentum.py clipped_data flow 11 1
python finetune_momentum.py clipped_data rgb 12 1
python finetune_momentum.py clipped_data flow 12 1